Add mediastats display on local video render
Azure-Samples/communication-services-web-calling-tutorial pull request #212
Opened 2024-01-16 18:14 UTC by enricohuang

## Purpose
* Add mediastats display on local video render

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2024-01-16 19:53 UTC, hkharoud approved these changes

2024-01-31 23:55 UTC, chriswhilar approved these changes

2024-02-01 16:33 UTC, csandjon approved these changes

2024-02-01 17:06 UTC, sharifrahaman requested changes

2024-02-01 17:06 UTC, sharifrahaman commented on Project/src/MakeCall/VideoSendStats.js
> +export default class VideoSendStats extends React.Component {
nit: could be functional component. Both functional and class component has pros and cons. Looks like functional component is preferable and the trends.

2024-02-01 20:40 UTC, enricohuang commented on Project/src/MakeCall/LocalVideoPreviewCard.js
> +                        <VideoSendStats videoStats={this.state.videoStats} />
We cannot omit `<h4 className="video-stats">`. Without this tag, the videosendstats div won't overlay on top of local video preview

2024-02-01 20:46 UTC, sharifrahaman approved these changes

2024-02-01 21:18 UTC, merged